### ISSUE TITLE
CodeReview in Progress

### ISSUE THREAD

**Issue by zzooppii** [tokamak-network/L2-Assets-Migration#17]
1. branch : https://github.com/tokamak-network/L2-Assets-Migration/tree/codeReview
2. commit hash: 691c53c2939f695f008f4925c2c2f008f89529a4
3. Expected review duration : 6 of business days
4. Review completion deadline : 2024.07.26
5. Contract Explain : [notion1](https://www.notion.so/tokamak/EN-83befd30adff4493bec28a1513260789#df5eeeb2bfe44ae2abc4e6dfe0cded15), [notion2](https://www.notion.so/tokamak/Claim-Model-9610176ef8c7474689485d1dde2c05f3?pvs=4#7ea692f7256c46e186a8198452a64a93)
6. Contract Scope : https://www.notion.so/tokamak/Contract-review-request-form-28c5ad1ec3344c22af3b07b81345fa21?pvs=4#e572ce989e254209821b0f861b52cae5
7. How to Review : Anyone can freely participate as a reviewer and leave a problem by leaving an issue in the relevant repository. (Please refer to [this document](https://www.notion.so/tokamak/FBI-smart-contract-review-project-3fef6fd0ec404a3797dca1e2465213c9) for further details.)
8. reward rules :  Problems found are operated by a point system depending on the severity of the problem, and Reward is according to the points, The person who leaves a review with the same content first can get points.

**Comment by DevUreak** [comment]
Closed as there are no more comments
